name: Python Installation

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verify tests directory
      run: |
        ls -la
        ls -la tests

    - name: Run tests
      run: python -m unittest discover -s tests
